# Generated by Django 5.1.5 on 2025-12-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_ar', models.CharField(help_text='الاسم بالعربي', max_length=200)),
                ('name_en', models.CharField(help_text='English name', max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, help_text='الجرعة', max_length=200)),
                ('side_effects', models.TextField(blank=True, help_text='الآثار الجانبية')),
                ('warnings', models.TextField(blank=True, help_text='التحذيرات')),
                ('category', models.CharField(blank=True, help_text='تصنيف الدواء', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name_ar'],
            },
        ),
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='imageupload',
            name='confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score', null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='detected_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='api.medicine'),
        ),
    ]
